// Generated by scripts/build-docs-nav.mjs. Do not edit manually.

import type { DefaultTheme } from 'vitepress'

export const sidebar: DefaultTheme.SidebarItem[] = 
[
  {
    "text": "Introduction",
    "link": "/"
  },
  {
    "text": "Prerequisites",
    "link": "/prerequisites"
  },
  {
    "text": "Setup",
    "link": "/setup"
  },
  {
    "text": "Development",
    "link": "/development"
  },
  {
    "text": "Build",
    "link": "/build"
  },
  {
    "text": "Scripts",
    "link": "/scripts"
  },
  {
    "text": "License",
    "link": "/license"
  }
]
