import { mkdir, readFile, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { rewriteMarkdownLinks } from './docs-link-rewriter.mjs';
import { getHeadings, normalizeHeadingText, toAnchor } from './docs-slugger.mjs';

const scriptDir = path.dirname(fileURLToPath(import.meta.url));
const repoDir = path.resolve(scriptDir, '..');
const readmePath = path.join(repoDir, 'README.md');
const docsDir = path.join(repoDir, 'docs');
const navConfigPath = path.join(scriptDir, 'docs-nav.config.mjs');

/** Section titles to skip when splitting README into pages. */
const SKIP_SECTION_TITLES = new Set(['Table of contents', 'Documentation']);

/**
 * Parses markdown intro and top-level ## sections.
 *
 * @param {string} markdown Markdown contents.
 * @returns {{ intro: string; sections: { title: string; anchor: string; body: string }[] }}
 */
const parseIntroAndSections = (markdown) => {
  const firstSectionMatch = markdown.match(/\n## /);

  if (!firstSectionMatch || firstSectionMatch.index === undefined) {
    return { intro: `${markdown.trimEnd()}\n`, sections: [] };
  }

  const intro = `${markdown.slice(0, firstSectionMatch.index).trimEnd()}\n`;
  const body = markdown.slice(firstSectionMatch.index + 1);
  const matches = [...body.matchAll(/^## (.+)$/gm)];

  const sections = matches
    .map((match, index) => {
      const title = match[1].trim();
      const start = match.index ?? 0;
      const end =
        index + 1 < matches.length ? (matches[index + 1].index ?? body.length) : body.length;

      return {
        title,
        anchor: toAnchor(title),
        body: `${body.slice(start, end).trimEnd()}\n`,
      };
    })
    .filter((section) => !SKIP_SECTION_TITLES.has(section.title));

  return { intro, sections };
};

/**
 * Promotes markdown heading levels by one so a section page gets a single h1.
 *
 * @param {string} markdown Section markdown.
 * @returns {string} Markdown with promoted headings.
 */
const promoteHeadingLevels = (markdown) =>
  markdown
    .split('\n')
    .map((line) => {
      const match = /^(#{2,6})\s+(.+)$/.exec(line);

      if (!match) {
        return line;
      }

      return `${'#'.repeat(match[1].length - 1)} ${match[2]}`;
    })
    .join('\n');

/**
 * Builds a lookup map from heading anchors to their enclosing section page slug.
 *
 * @param {{ level: number; title: string; anchor: string }[]} headings Heading metadata.
 * @returns {Map<string, { slug: string; isSectionRoot: boolean }>}
 */
const buildAnchorMap = (headings) => {
  const anchorMap = new Map();
  let currentSectionSlug = null;

  for (const heading of headings) {
    if (heading.level === 2) {
      currentSectionSlug = heading.anchor;
      anchorMap.set(heading.anchor, { slug: heading.anchor, isSectionRoot: true });
      continue;
    }

    if (currentSectionSlug) {
      anchorMap.set(heading.anchor, {
        slug: currentSectionSlug,
        isSectionRoot: false,
      });
    }
  }

  return anchorMap;
};

/**
 * Ensures a directory exists before writing files into it.
 *
 * @param {string} dirPath Directory path.
 * @returns {Promise<void>}
 */
const ensureDir = async (dirPath) => {
  await mkdir(dirPath, { recursive: true });
};

/**
 * Serializes the nav manifest module from split sections.
 *
 * @param {{ title: string; anchor: string }[]} sections Section metadata.
 * @returns {string} TypeScript module source.
 */
const buildNavConfigFile = (sections) => {
  const navLines = [
    "  { kind: 'overview', title: 'Introduction' }",
    ...sections.map(
      (section) =>
        `  { kind: 'page', slug: ${JSON.stringify(section.anchor)}, title: ${JSON.stringify(normalizeHeadingText(section.title))} }`,
    ),
  ];

  const serializedNav = `[\n${navLines.join(',\n')},\n]`;

  return [
    '/**',
    ' * Ordered VitePress sidebar manifest for canonical docs pages.',
    ' *',
    ' * Generated by scripts/split-readme.mjs. Edit to reorder nav or add pages.',
    ' * Run `pnpm docs:build:nav` to regenerate the sidebar.',
    ' */',
    '',
    '/** @typedef {{ name: string; source: string; title: string; targetDir?: string }} SyncedDocPage */',
    '',
    '/** @type {SyncedDocPage[]} Optional synced pages copied from elsewhere in the repo. */',
    'export const syncedPages = [];',
    '',
    '/**',
    ' * Top-level docs navigation entries in sidebar order.',
    ' *',
    ' * @type {Array<',
    ' *   | { kind: \'overview\'; title: string }',
    ' *   | { kind: \'page\'; slug: string; title: string; maxDepth?: number; pinnedBottom?: true }',
    ' *   | { kind: \'group\'; slug: string; title: string; pages: SyncedDocPage[] }',
    ' * >}',
    ' */',
    `export const docsNav = ${serializedNav};`,
    '',
    '/** Slugs of canonical overview pages committed under docs/<slug>/index.md. */',
    'export const groupOverviewSlugs = new Set(',
    '  docsNav.filter((entry) => entry.kind === \'group\').map((entry) => entry.slug),',
    ');',
    '',
    '/** Slugs of canonical guide pages committed as docs/<slug>.md. */',
    'export const canonicalPageSlugs = new Set(',
    '  docsNav.filter((entry) => entry.kind === \'page\').map((entry) => entry.slug),',
    ');',
    '',
  ].join('\n');
};

const readme = await readFile(readmePath, 'utf8');
const { intro, sections } = parseIntroAndSections(readme);
const headings = getHeadings(readme);
const anchorMap = buildAnchorMap(headings);

await ensureDir(docsDir);
await writeFile(path.join(docsDir, 'index.md'), rewriteMarkdownLinks(intro, { anchorMap }));

for (const section of sections) {
  const pageMarkdown = promoteHeadingLevels(section.body);
  await writeFile(
    path.join(docsDir, `${section.anchor}.md`),
    rewriteMarkdownLinks(pageMarkdown, { anchorMap }),
  );
}

await writeFile(navConfigPath, buildNavConfigFile(sections));

console.log(
  `Split README.md into docs/index.md and ${sections.length} section page(s); updated ${path.relative(repoDir, navConfigPath)}`,
);
